### ISSUE TITLE
Connection string incompatible with azure SQL Server

### ISSUE THREAD

**Issue by bestekov** [archimag/cl-mssql#9]
According to the Azure docs, `USE` is invalid for switching databases: https://learn.microsoft.com/en-us/sql/t-sql/language-elements/use-transact-sql?view=sql-server-ver15

This line: https://github.com/archimag/cl-mssql/blob/045602a19a32254108f2b75871049293f49731eb/src/connection.lisp#L73

Apparently may be causing issues?

This came from an issue in the `pgloader` library: https://github.com/dimitri/pgloader/issues/1324#issuecomment-1220781465

**Comment by archimag** [comment]
Sorry, I don't use CL и MSSQL for many years, but I will do merge if you can solve this problem.
